development:
  adapter: postgresql
  database: peek_api_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: peek_api_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: peek_api_prod
  pool: 5
  timeout: 5000